// Code generated by trilha. DO NOT EDIT.

//go:generate trilha gen

package main

import (
	"embed"

	trilha "github.com/emersonjoe/trilha"
	app "github.com/emersonjoe/voice-based-customer-service/app"
	app_agente "github.com/emersonjoe/voice-based-customer-service/app/agente"
	app_api_chamados "github.com/emersonjoe/voice-based-customer-service/app/api/chamados"
	app_api_chamados_id__status "github.com/emersonjoe/voice-based-customer-service/app/api/chamados/id_/status"
	app_api_hello "github.com/emersonjoe/voice-based-customer-service/app/api/hello"
	app_api_tools_abrir_chamado_tecnico "github.com/emersonjoe/voice-based-customer-service/app/api/tools/abrir_chamado_tecnico"
	app_api_tools_enviar_segunda_via_boleto "github.com/emersonjoe/voice-based-customer-service/app/api/tools/enviar_segunda_via_boleto"
	app_api_tools_solicitar_religue_confirmacao "github.com/emersonjoe/voice-based-customer-service/app/api/tools/solicitar_religue_confirmacao"
	app_api_voz_assinada "github.com/emersonjoe/voice-based-customer-service/app/api/voz/assinada"
	app_painel "github.com/emersonjoe/voice-based-customer-service/app/painel"
	app_painel_chamado_id_ "github.com/emersonjoe/voice-based-customer-service/app/painel/chamado/id_"
)

//go:embed public
var publicFS embed.FS

// newApp builds the application. Tests can call it and use a.Handler().
func newApp() *trilha.App {
	cfg := trilha.ConfigFromEnv()
	cfg.Public = trilha.PublicFS(publicFS, "public")
	a := trilha.New(cfg)
	if err := app.Setup(a); err != nil {
		trilha.Fatal(err)
	}
	a.SetRootLayout(app.Layout)
	a.SetNotFound(app.NotFound)
	a.Register(trilha.Route{
		Pattern: "/",
		Page:    app.Page,
		Layouts: []trilha.LayoutFunc{app.Layout},
	})
	a.Register(trilha.Route{
		Pattern: "/agente",
		Page:    app_agente.Page,
		Layouts: []trilha.LayoutFunc{app.Layout},
	})
	a.Register(trilha.Route{
		Pattern: "/api/chamados",
		Kind:    app_api_chamados.Kind,
		Methods: map[string]trilha.HandlerFunc{
			"GET": app_api_chamados.GET,
		},
	})
	a.Register(trilha.Route{
		Pattern: "/api/chamados/{id}/status",
		Kind:    app_api_chamados.Kind,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_api_chamados_id__status.POST,
		},
	})
	a.Register(trilha.Route{
		Pattern: "/api/hello",
		Methods: map[string]trilha.HandlerFunc{
			"GET": app_api_hello.GET,
		},
	})
	a.Register(trilha.Route{
		Pattern: "/api/tools/abrir_chamado_tecnico",
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_api_tools_abrir_chamado_tecnico.POST,
		},
	})
	a.Register(trilha.Route{
		Pattern: "/api/tools/enviar_segunda_via_boleto",
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_api_tools_enviar_segunda_via_boleto.POST,
		},
	})
	a.Register(trilha.Route{
		Pattern: "/api/tools/solicitar_religue_confirmacao",
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_api_tools_solicitar_religue_confirmacao.POST,
		},
	})
	a.Register(trilha.Route{
		Pattern: "/api/voz/assinada",
		Methods: map[string]trilha.HandlerFunc{
			"GET": app_api_voz_assinada.GET,
		},
	})
	a.Register(trilha.Route{
		Pattern: "/painel",
		Page:    app_painel.Page,
		Layouts: []trilha.LayoutFunc{app_painel.Layout, app.Layout},
	})
	a.Register(trilha.Route{
		Pattern: "/painel/chamado/{id}",
		Page:    app_painel_chamado_id_.Page,
		Layouts: []trilha.LayoutFunc{app_painel.Layout, app.Layout},
	})
	return a
}

func main() {
	trilha.Run(newApp())
}
